### ISSUE TITLE
add variation bounds to ensemble chart

### ISSUE THREAD

**Issue by ashlinrichardson** [ecsendmail/MultiverseContagion#17]

**Comment by ashlinrichardson** [comment]
and envelopes!

**Comment by ashlinrichardson** [comment]
still need this as well as envelopes?

**Comment by ashlinrichardson** [comment]
This could be accomplished by Density Estimation as 
@kmoselle indicated  ss in Fig. 3 of:
"Measurability of the epidemic reproduction number in data-driven contact networks"
Quan-Hui Liu a,b,c , Marco Ajelli c,d , Alberto Aleta e,f , Stefano Merler d , Yamir Moreno e,f,g , and Alessandro Vespignani c,g,1
a

**Comment by kmoselle** [comment]
I believe density is just what we are looking for.


But as I speculate - would it be possible to locate longitudinal outliers, e.g., trials that start in one high probability region and then end up in a low probability region where most of the trials that start in a high probability region don't go???


If we were greedy we would want the density gradient and then have the capacity to play a movie where each of the trials that contribute towards that density depiction get highlighted so that we could use our eyeballs to catch the outliers or atypical cases and then look at them more closely, e.g., look at the transmission trees for a select set./Ken


________________________________

**Comment by ecsendmail** [comment]
How would you assign high and low probabilities? Do you mean frequency?

Ernie

**Comment by ecsendmail** [comment]
If you repeat 1000 trials would you get the same envelope?
